### ISSUE TITLE
Android Studio BumbleBee issues - unusable

### ISSUE THREAD

**Issue by JasonTheDynamite** [skrugly/mirakle#100]
If I use: 
rsyncFromRemoteArgs += ["--info=progress2"]
or
rsyncToRemoteArgs += ["--info=progress2"]

i get this error:
![image](https://user-images.githubusercontent.com/18309065/151389441-bec5fa5f-3422-4b66-a1f7-d11085488426.png)

Before updating to android studio bubmlebee everything worked fine

If I comment above lines from ./gradle/init.d file - almost  everything works. Build etc.
But does not build lastest version of my code. If I make any changes to my code - they are not reflected on emulator and/or physical device. Cleaning etc does not help.
If I turn off mirakle - everything starts working fine.

Version: 1.4.3

At this point it's unsable.

Sender: macOS Monterey, rsync: 3.2.3
Receiver (build happens here): ubuntu 20.04, rsync: 3.1.3

After changing anything i any .gradle file on local machine - everything works fine and changes are reflected on emulator.

**Comment by skrugly** [comment]
Thanks for the report, I encounter the same issue. Working on a fix.

**Comment by skrugly** [comment]
Error message that you posted says you have rsync `2.6.9`.
You should follow [these instructions](https://dev.to/al5ina5/updating-rsync-on-macos-so-you-re-not-stuck-with-14-year-old-software-1b5i) to get it updated.
But in my case Gradle still uses 2.6.9 when running from Android Studio. Didn't found a fix for this yet.

**Comment by JasonTheDynamite** [comment]
Yes it indicates that I have rsync 2.6.9 its true because MacOS uses 2.6.9 and it can not be changed.
BUT: I use rsync version 3.2.3 installed using homebrew. Technically everybody on MacOS has at least two versions of rsync. One for the system because apple decided that way and the second is being used by the user. Before BumbleBee Android studio used that second newer version of RSYNC and there were no issues. I have everything set up correctly in my bashrc etc files. After updating to bumblebee suddenly I get this error and it indicates that I use 2.6.9 which is strange...

**Comment by skrugly** [comment]
Try to add these lines to `mirakle_init.gradle`
```
taskGraph.whenReady { taskGraph ->
    if (taskGraph.hasTask(":uploadToRemote")) {    
        def argsCopy = gradle.rootProject.uploadToRemote.args
        gradle.rootProject.uploadToRemote.commandLine = "/usr/local/bin/rsync"
        gradle.rootProject.uploadToRemote.args = argsCopy 
    }
}
```

**Comment by JasonTheDynamite** [comment]
ok but where ? beginngin ? end ? in rootProject ?

currently this file looks like this:
![image](https://user-images.githubusercontent.com/18309065/151537888-c9a94371-4bf7-4c20-8cc0-c47cf4d5a997.png)
I know it looks awful - I experiment all the time with it :)

**Comment by skrugly** [comment]
Add it to the end of the file

**Comment by JasonTheDynamite** [comment]
![image](https://user-images.githubusercontent.com/18309065/151538290-746958aa-8cc2-4b1f-a027-f57ebd084bc3.png)
![image](https://user-images.githubusercontent.com/18309065/151538498-cd67371b-ac47-4e2d-a97d-ab60a3a74ff5.png)

**Comment by skrugly** [comment]
Could you be more specific about that issue, where it comes from. Please send last lines from the build log.
And also replace the lines in `mirakle_init.gradle` by new ones:
```
taskGraph.whenReady { taskGraph ->
    if (taskGraph.hasTask(":uploadToRemote")) {    
        def argsCopy = gradle.rootProject.uploadToRemote.args
        gradle.rootProject.uploadToRemote.commandLine = "/usr/local/bin/rsync"
        gradle.rootProject.uploadToRemote.args = argsCopy 
    }

    if (taskGraph.hasTask(":downloadFromRemote")) {    
        def argsCopy = gradle.rootProject.downloadFromRemote.args
        gradle.rootProject.downloadFromRemote.commandLine = "/usr/local/bin/rsync"
        gradle.rootProject.downloadFromRemote.args = argsCopy 
    }
}
```

**Comment by JasonTheDynamite** [comment]
Performing CLEAN and/or BUILD:
![image](https://user-images.githubusercontent.com/18309065/151539646-81ee2c4d-7502-444d-812d-7d57e716f3b3.png)

There is nothing more. This is all I can find.

**Comment by skrugly** [comment]
Could you click on the first line which contains `Build ... 2 sec, 518 ms`, it should open full log window

**Comment by skrugly** [comment]
Also try to disable `downloadInParallel` and `fallback`

**Comment by JasonTheDynamite** [comment]
![image](https://user-images.githubusercontent.com/18309065/151542096-8fc37b07-5a68-407a-825c-5507a74ce721.png)


No such file or directory probably means there is no such thing as: usr/local/bin/rsync
This folder does not contain rsync.

Contents of .bash_profile located in users/MyUserName/
![image](https://user-images.githubusercontent.com/18309065/151541584-616c7e91-255d-4b09-81b4-17d50b6a0859.png)

Everything was fine until I upgraded to bumbleBee. Rsync was configured according to this and other tutorials - how to do it on MacOS

**Comment by skrugly** [comment]
Invoke `which rsync` in terminal to find where is rsync installed and replace these lines which I send with your path.
```
gradle.rootProject.uploadToRemote.commandLine = "YOUR_PATH_TO_RSYNC_HERE"
gradle.rootProject.downloadFromRemote.commandLine = "YOUR_PATH_TO_RSYNC_HERE"
```

**Comment by JasonTheDynamite** [comment]
which rsync:
/opt/local/bin/rsync

Started working but:

![image](https://user-images.githubusercontent.com/18309065/151543222-7a0dd665-c698-4560-a70f-afdd0a0ab580.png)

**Comment by skrugly** [comment]
Check that you have at least `com.android.tools.build:gradle:7.1.0` and `Gradle 7.3`.
And do in Android Studio `File - Invalidate Caches`

**Comment by JasonTheDynamite** [comment]
![image](https://user-images.githubusercontent.com/18309065/151544218-bf56bd07-ff53-4fbd-a630-d6ebbc2cbc4a.png)
![image](https://user-images.githubusercontent.com/18309065/151544263-819bbc94-8be3-43b3-985d-ced4f1527497.png)

Started working without invalidating caches.

Yesterday when I was searching for any kind of solution to this problem I used gradle 7.1.0 and it did not work.
Now it's ok. 

I will get back after testing. It might take more than 3 days :)
Thanks for help.

Tell me please - is this my fault or bumblebee has some changes which impact mirakle ? or maybe something is messed up with rsync ?

**Comment by skrugly** [comment]
Glad we get it working finally!
Seems it's some bumblebee change, I'm still investigating it.

**If someone else has the same issue in Android Studio Bumblebee please let me know in this issue.**

**Comment by skrugly** [comment]
https://issuetracker.google.com/issues/216364005?pli=1

**Comment by skrugly** [comment]
It's solely Bumblebee issue, closing this.
