### ISSUE TITLE
Plugin with id 'com.android.application' not found in Android Studio

### ISSUE THREAD

**Issue by weidenka** [skrugly/mirakle#104]
I try to use miracle to build an android app on a remote machine. Works (almost) like a charm. Except when running the `assemble` task from AndroidStudio. Then I get 
```shell
 Plugin with id 'com.android.application' not found.
```
When I run the very same task from the command line it works. So this is obviously not a bug in miracle. Any idea how to avoid this?

**Comment by skrugly** [comment]
Could you check in again using mirakle `1.5.3-RC-9` and Gradle 7.5+.

**Comment by weidenka** [comment]
Seems to be ok with 1.6.0
