### ISSUE TITLE
Tasks fails instantly

### ISSUE THREAD

**Issue by matheusfinatti** [skrugly/mirakle#107]
Any task I try to run fails instantly with the following error (e.g. `$ ./gradlew assembleDebug`):

```
Executing Gradle tasks as part of a build without a settings file is not supported. Make sure that you are executing Gradle from a directory within your Gradle project. Your project should have a 'settings.gradle(.kts)' file in the root directory.
```

Can't figure it out what's happening. I have not configured anything else, just using the barebones `mirakle_init.gradle` file located in my home directory `.gradle/init.d/mirakle_init.gradle`.

```groovy
initscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'io.github.adambl4:mirakle:1.5.0'
    }
}

apply plugin: Mirakle

rootProject {
    mirakle {
        host "louise"
    }
}
```

Where "louise" is my remote machine (which I can SSH with `$ssh louise`).
Code isn't uploaded, I can't see anything in the remote machine and removing this script reverts everything back to normal.

**Comment by skrugly** [comment]
Hey, try to upgrade your Gradle to the latest version `7.4.2`.
