### ISSUE TITLE
Proposal: simple on/off button plugin for IDEA base IDE's

### ISSUE THREAD

**Issue by dsvoronin** [skrugly/mirakle#11]
One additional icon like Gradle's offline toggle with single function: append `-x mirakle` to command line arguments.

Seems like the only missing feature to perfect UX :)

p.s. Will try to contribute next week

**Comment by skrugly** [comment]
Actually there is  `Preferences`>`Build, Execution, Deployment`>`Compiler`>`Command-line Options` where you can pass `-x mirakle`. 
Maybe it's possible to bind a hot key to pass that param, using [Idea Macros](https://www.jetbrains.com/help/idea/recording-macros.html) for example.
I've tried a bit without success, but it looks promising.

**Comment by skrugly** [comment]
And what is common cause to `-x mirakle` in your case?
If it's due to server connection issue, I'm planning to introduce `mirakle { fallback = true }` config option which will execute build locally if upload to remote failed.

**Comment by dsvoronin** [comment]
I work on multiple gradle-based projects, and from different places (office/home/cafe), build server accessible only via VPN, and sometimes it's completely ok not to use it (small project, like mirakle for example), sometimes i even work without Internet connection at all, e.g. `--offline` mode.

Fallback looks fine, but what kind of strategy do you plan to use to detect server availability?
Looks like there will be a noticeable overhead for fallback builds if host resolved, but connection would time out.

**Comment by Mishkun** [comment]
I think it can be made adding two tasks goOffline and goOnline which would change some config file lying near the mirakle-init script
