### ISSUE TITLE
gradlew not found after updating to 1.5.1

### ISSUE THREAD

**Issue by oscar-tu-lotero** [skrugly/mirakle#110]
After updating from mirakle:1.5.0 (works OK) to mirakle:1.5.1, I see this error when I try a build:

```
> Task :executeOnRemote
bash: ~/mirakle/my_project/gradlew: No existe el archivo o el directorio
```

**Comment by skrugly** [comment]
Hey, could you provide a little more details:
1. What is your `rsync --version` on local and remote machines?
2. What is your local and remote operation system?
3. Is that folder exist if you check it through `ssh your_remote 'ls ~/mirakle/my_project'`

**Comment by oscar-tu-lotero** [comment]
Hi,

Local (macOS Monterey 12.4):
rsync  version 2.6.9  protocol version 29

Remote (Ubuntu 20.04.4 LTS):
rsync  version 3.1.3  protocol version 31

Yes, I have checket that the folder exists in the remote machine.

**Comment by skrugly** [comment]
Could you do `brew install rsync` on macos, it will update your local rsync to the newer version 3.2.4. I believe it may help.

**Comment by oscar-tu-lotero** [comment]
I have updated rsync on macOS,  to version 3.2.4  protocol version 31. 
But the same problem still happens.

**Comment by andrey-bolduzev** [comment]
Can confirm I'm seeing the same error with Linux on both machines.

**Comment by JSpiner** [comment]
I also worked fine in 1.5.0, but it doesn't work in 1.5.1.

rsync is successfully worked. and I can see the synced folder.
but executeOnRemote fail like below.

> Task :executeOnRemote
> bash: ~/mirakle/KakaoT/gradlew: No such file or directory

I think, gradle's `project.task<Exec>` wraps `args` once more with quotes(`"`).
for example,

```bash
$ ssh mainframer "~/mirakle/my_project/gradlew"
// works fine

$ ssh mainframer "\"~/mirakle/my_project/gradlew\""
bash: ~/mirakle/my_project/gradlew: No such file or directory
// an error like 1.5.1
```

@Adambl4 
This code seems to have an effect, I think you can remove the quotes.
https://github.com/Adambl4/mirakle/commit/c28383144c01148333b4731dcf4240758cfd892e#diff-5c5f3cc932f8a1ca09848c5c2466a8ce3872748600b75821773c3cedfb0e78b8R146

**Comment by ghost** [comment]
I can confirm that it works when quotes are removed

**Comment by skrugly** [comment]
Thank you guys for the report. It's weird bug since it worked well in my macos to remote linux environment.
I've removed the quotes. The only downside is without quotes it doesn't work on Windows remote machine.
