### ISSUE TITLE
Running tests broken with composite builds

### ISSUE THREAD

**Issue by marcorighini** [skrugly/mirakle#114]
https://github.com/marcorighini/KMM-Composite-Build
I found that, also with the new fixes, running the tests from the IDE (Android Studio) using composite builds is broken.
Trying to run `aSampleTest` (from the sample project above) results in  
```
Project directory '/Users/marcox/projects/KMM-Composite-Build/sample-kmm/shared' is not part of the build defined by settings file '/Users/marcox/projects/KMM-Composite-Build/sample-kmm/settings.gradle.kts'. If this is an unrelated build, it must have its own settings file.
```
but it work correctly if I disable Mirakle.

**Comment by skrugly** [comment]
Thanks, I see, looking for a fix.

**Comment by skrugly** [comment]
Could you check `io.github.adambl4:mirakle:1.5.3-RC-2`

**Comment by marcorighini** [comment]
I'm getting `Test events were not received`

**Comment by skrugly** [comment]
Seems it started to work with composite builds, but now it stumbles over this error #83

**Comment by skrugly** [comment]
@marcorighini check please does your tests work with `io.github.adambl4:mirakle:1.5.3-RC-4`

**Comment by marcorighini** [comment]
Sorry for the late reply, still happening with the new version

**Comment by skrugly** [comment]
what is your Android Studio Version?

**Comment by marcorighini** [comment]
Android Studio Chipmunk | 2021.2.1 Patch 1
