### ISSUE TITLE
Total transfer progress is not working for downloadFromRemote task

### ISSUE THREAD

**Issue by timurRadikovich** [skrugly/mirakle#125]
Hi! I can't see a transfer progress for downloadFromRemote task. I've tried using --info=progress2 and --info=progress1 as described here https://github.com/Adambl4/mirakle/blob/development/docs/TIPS_AND_TRICKS.md#show-total-transfer-progress but I can't see any difference in the output. By the way I can see "sent" and "received" for uploadToRemote task.

![Screenshot 2022-09-29 103601](https://user-images.githubusercontent.com/60694122/192970672-12752c95-16a2-47e2-9588-702eaf6ce858.png)

![Screenshot 2022-09-29 103629](https://user-images.githubusercontent.com/60694122/192970589-a8bc7775-8fa3-4fd9-b9d7-3b766e19307b.png)

**Comment by skrugly** [comment]
Here is how it looks for me if I add to rsync args. `"--info=progress2"`
```
    388,004,750  95%   10.78MB/s    0:00:34 (xfr#16358, to-chk=0/23994)
```
Check your `rsync --version` on local machine and update if it is too old. Mine is `3.2.4`.

**Comment by timurRadikovich** [comment]
My rsync version is 3.2.3, not too old

**Comment by timurRadikovich** [comment]
The problem was in -q option. Removing it fixed the problem
