### ISSUE TITLE
AS gradle console is empty

### ISSUE THREAD

**Issue by dmitriigriazin** [skrugly/mirakle#18]
Execution of any gradle task sometimes leaves the console log empty. Can't see the ways to reproduce, it's unstable, but I have it pretty often. Once the console got empty, only the studio restart helps.

Are there any ways to see the log, maybe to redirect it to the other output?

**Comment by skrugly** [comment]
Does console become empty immediately after starting a task or during parcticular stage of execution, for example during `uploadToRemote` or `executeOnRemote`?

**Comment by dmitriigriazin** [comment]
It's becomes empty immediately, no output there at all. 
One starts a task, the previous log is erased and that's it.

**Comment by skrugly** [comment]
Next time when you faced this issue, click `Help -> Show log in finder` and check is there anything helpful in the Android Studio log.
I think it's possible to redirect Gradle output to a file, but have not found a way yet.
