### ISSUE TITLE
Update to gradle 4.10

### ISSUE THREAD

**Issue by fat-fellow** [skrugly/mirakle#20]
Hi. I am using this `1.3.0-RC1` to upload building process on remote server.
I updated to gradle `4.10` and faced with project building doesn't work.
The trouble is in `utils.kt`
`val field = AbstractTask::class.java.getDeclaredField("services")` should be changed to 
`val field = AbstractTask::class.java.getDeclaredField("_services")` due to renaming this field in `AbstractTask` class in `gradle-api-4.10`
I had done it locally and then uploaded the script to local maven repository and there are workaround for switching between the proper versions of gradle in script (i called it `1.3.0-RC-2`):
```initscript {
    repositories {
        maven { url "myhost/rep1" }
        maven { url "myhost/jcenter" }
    }
    
    ext.gradleVersion = gradle.gradleVersion.split("\\.")

    if (Integer.valueOf(ext.gradleVersion[0]) < 5 && Integer.valueOf(ext.gradleVersion[1]) < 10) {
        ext.mirakle = "1.3.0-RC-1"
    } else {
        ext.mirakle = "1.3.0-RC-2"
    }
    
    dependencies {
        classpath "com.instamotor:mirakle:$mirakle"      
    }
}
```

**Comment by lukaville** [comment]
@Adambl4 looks like a critical issue since the latest stable Android Gradle Plugin 3.3.0 requires Gradle 4.10.1+
