### ISSUE TITLE
Any way to run android gradle "install" commands locally? 

### ISSUE THREAD

**Issue by ghost** [skrugly/mirakle#21]
One side effect of running `./gradlew install{flavor/buildtype/whatever}` is that the install task fails with a `DeviceException: No connected devices!` error (because the install task is running on the remote machine, which isn't running the emulator).

An obvious workaround is to just use an `assembe` task instead and then manually install/run the APK locally after the Gradle task is finished, but I'm curious if there's a workaround or if you guys have a better solution. Thanks!

**Comment by erawhctim** [comment]
Thinking on this more: would it make sense to disable remote execution if the script could detect that (1) a device-specific gradle task is being run (e.g `installWhatever` vs `assembleWhatever`) _and_ (2) the build/output APK directory already contained an APK from a previous remote execution command? 

That way, you could run something like `./gradlew aSD iSD` and let the assembly task run remotely and the install command run locally?

**Comment by skrugly** [comment]
Hey guys, finally I managed to implement this future, if you are still interested please take a look at PR #49. 
Your feedback will be very helpful!

@erawhctim @ishaan1995 @MikhailZisman @andrey-bolduzev
