### ISSUE TITLE
Any way to update the gradle plugin to use an 'opt-in' mechanism and only run when passing in the CLI flag?

### ISSUE THREAD

**Issue by erawhctim** [skrugly/mirakle#22]
I like the simplicity of always running (when configured properly) and disabling remote execution via the `-x mirakle` flag, however I'm curious if the _reverse_ is possible. I'd like to take a stab at either forking this and implementing such a feature on my own fork, or integrating this as a feature back into mirakle, but would love some guidance on where to start and/or if you think this is a good idea, easy to accomplish, crazytown, etc

**Comment by skrugly** [comment]
Thanks for the idea, now it's possible, check [readme](https://github.com/Instamotor-Labs/mirakle#opt-in-execution)
