### ISSUE TITLE
Can't use the fallback option if the mainframer config exists

### ISSUE THREAD

**Issue by wakwak3125** [skrugly/mirakle#27]
According to [these](https://github.com/Instamotor-Labs/mirakle/blob/development/plugin/src/main/kotlin/Mirakle.kt#L63...L64) lines,

If the mainframer config already exists at the project, mirakle can't fallback to local build.
Are there any solutions to fallback to local build even if the mainframer config exists?

Thanks

**Comment by skrugly** [comment]
I will make a fix for this soon.

**Comment by skrugly** [comment]
Thanks for reporting.
Fixed in `com.instamotor:mirakle:1.3.2`
