### ISSUE TITLE
not working with android studio 3.6

### ISSUE THREAD

**Issue by Nemunas** [skrugly/mirakle#32]
build completes without apparent errors

debug install then throws an error and does not run:

Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: No outputs for the main artifact of variant: debug

**Comment by skrugly** [comment]
Yep, I have the same problem using Android Studio 3.6.
But it works good on Android Studio 4.0 Beta 3. Use this version instead if you can, probably I will not investigate that issue on 3.6 since it will be outdated soon.

**Comment by Nemunas** [comment]
I'm having the same issue on android studio 4.0 beta 3 as well...

**Comment by skrugly** [comment]
Check that also you have updated version of android gradle plugin
```
classpath 'com.android.tools.build:gradle:4.0.0-beta03'
```

**Comment by Nemunas** [comment]
Ah, i hadn't done that.

Getting a new error now: 

java.io.FileNotFoundException: /Users/meatball/dev/Aurora/build/build-attribution/androidGradlePluginAttributionData (No such file or directory)
                               0% :app:checkDebu?licateClasses (0:00.313)
> /Users/meatball/dev/Aurora/build/build-attribution/androidGradlePluginAttributionData (No such file or directory)

**Comment by skrugly** [comment]
Perform a `clean` task or do `Build -> Rebuild project` in AS when you see this error.
This is happening due to new Build Analyzer included into AS 4.0 and it doesnt work good with mirakle so far, will look for a fix.

**Comment by Nemunas** [comment]
Yup, that fixed it!

Thanks so much for the help!
