### ISSUE TITLE
Problem with find ANDROID_SDK_ROOT

### ISSUE THREAD

**Issue by santiihoyos** [skrugly/mirakle#35]
Hi,

I have 2 machines:
- Server Linux Ubuntu with android environment
- Laptop MacBookPro

when I run ./gradlew build from laptop it connects with ubuntu and start build but crash with this error:

note: I tried to do error instrucctions but does't work :S

regards and thanks for your help.

```
MacBook-Pro-de-Santiago:projectAndroid santi$ ./gradlew build

> Configure project :
Here's Mirakle 1.3.2. All tasks will be executed on santiPc.

> Task :executeOnRemote

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/santi/Desarrollo/android/projectAndroid/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

> Configure project :app
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

> Task :mirakle FAILED
Total time : 1.316 secs
Task uploadToRemote took: 0.436 secs
Task executeOnRemote took: 0.726 secs
Task downloadFromRemote took: 0.129 secs
4 actionable tasks: 4 executed
```

**Comment by santiihoyos** [comment]
Closed, fixed setting ANDROID_SD_ROOT in mac terminal

**Comment by JagdeepNDiscovery** [comment]
@santiihoyos how did you fix this issue? I have set this on the mac still having the issue. Did u remove or add local.properties file?

**Comment by santiihoyos** [comment]
> @santiihoyos how did you fix this issue? I have set this on the mac still having the issue. Did u remove or add local.properties file?

Yes, I have created a local.properties file in remote.

The problem was that explanation's error saids: 

> > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '{**MAC_ROUTE_TO_MY_PROJECT**}/local.properties'.

And my project already had that file in local project (on mac) but rsync didn't upload it.
I had to create it manually.
I think that error explanation should said something like  '{**REMOTE_ROUTE_OF_PROJECT**}/local.properties'.

regards and thanks. ✌🏼

**Comment by JagdeepNDiscovery** [comment]
@santiihoyos Thank you for the above. Yes adding the `local.properties` manually to the remote folder worked. I checked the source code of this plugin and found that file `local.properties` was ignored from rsync, hence any changes to that were not being transferred.

Wasted a-lot of time trying to setup environment variables but SSH doesn't like it. hence `local.properties` is the simplest solution.

Thank you for your help

**Comment by skrugly** [comment]
Yes, `local.properties` is ignored 'cause there is little chance it will have the same sense for remote machine like for your local one.

I will point to this issue in docs somehow.
