### ISSUE TITLE
Task 'Beta' not found when running in Android Studio 4.1 Beta 1 or newer

### ISSUE THREAD

**Issue by marcorighini** [skrugly/mirakle#38]
**Configuration**
Mirakle 1.3.3 (but tested also with 1.3.1 and problem is there too)
Android Studio Build: 4.1 Beta 1 
Version of Gradle Plugin: 3.6.3 
Version of Gradle: 6.2.2 
Version of Java: openjdk version "1.8.0_202-release" 
OS: MacOS

**Steps to reproduce**
`Task :executeOnRemote`
During `Configure project :app`

**Error**
```
* What went wrong:
Task 'Beta' not found in root project ...
```

Similar problem on Android Studio 4.2 Canary 1

```
* What went wrong:
Task 'Canary' not found in root project ...
```

**Notes**
- it was working with Android Studio 4.1 Canary 10
- no error when mirakle disabled (-x mirakle)

**Comment by nikita-toropov** [comment]
If anyone needs a workaround:

```
initscript {
    ...
}

def excludedProjectProperties = [
    "android.injected.studio.version"
]

startParameter.projectProperties.removeAll { projectProperty, _ ->
    projectProperty in excludedProjectProperties 
}

apply plugin: Mirakle

rootProject {
    ...
}
```

**Comment by skrugly** [comment]
Fixed in `com.instamotor:mirakle:1.3.4`. 
Sorry for the delay.
