### ISSUE TITLE
Suggestion: Add optional param to skip downloading artifacts

### ISSUE THREAD

**Issue by andrey-bolduzev** [skrugly/mirakle#41]
I often find myself in a situation where I want to dispatch some long-running Gradle task (like heavy linting) to a remote machine while skipping downloading artifacts after the remote task is finished so that I can continue running other Gradle tasks locally and they wouldn't be broken by compiled class files from the remote machine being injected into the build folder in the middle. Or maybe I don't even want to stay on the same code: quickly dispatch a task, and switch to a different branch.

I was imagining having an extra command-line argument like `-PnoDownload` which would just prevent the "download from remote" part from happening.

Not sure if anyone else would find this useful.

**Comment by skrugly** [comment]
I see what you mean. Does it work for you if you add `--dry-run` to rsync args?
```
rsyncFromRemoteArgs += ["--dry-run"]
```

**Comment by andrey-bolduzev** [comment]
I hadn't thought about that but it worked perfectly. I parameterized the rsync args in the config:

```groovy
...

rootProject {
    mirakle {
        ...

        if (!project.hasProperty("dl")) {
            rsyncFromRemoteArgs += ["--dry-run"]
        }
    }
}
```

I'm closing this issue as resolved. Thank you for your help!
