### ISSUE TITLE
Feature request: display connection speed and transferred data for upload/download tasks

### ISSUE THREAD

**Issue by MyDogTom** [skrugly/mirakle#51]
Currently `mirakle` shows something like that
```
Total time : 9 mins 3.816 secs
Task uploadToRemote took: 4.136 secs
Task executeOnRemote took: 7 mins 34.594 secs
Task downloadFromRemote took: 1 mins 25.028 secs
4 actionable tasks: 4 executed
```

Would it be possible to also display how much data was transferred and/or what was the connection speed?

I think it might be beneficial to see that data to easily detect connection issues and/or tasks that produces big results.

**Comment by skrugly** [comment]
Hey, mirakle uses rsync under the hood to sync files and your request can be easily achived using rsync `--info` flag. See [Tips and Tricks doc.](https://github.com/Adambl4/mirakle/blob/development/docs/TIPS_AND_TRICKS.md#show-total-transfer-progress)

**Comment by MyDogTom** [comment]
thank you! 
```
mirakle {
    rsyncToRemoteArgs += ["--info=progress2"] 
    rsyncFromRemoteArgs += ["--info=progress2"] 
}
```
did the trick. Initially it failed because I had an old `rsync` version on my Mac
```
rsync: --info=progress2: unknown option
rsync error: syntax or usage error (code 1) at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54.120.1/rsync/main.c(1337) [client=2.6.9]
```
after updating `rsyc` everything works.
