### ISSUE TITLE
APK does not install on Android Studio 4.1

### ISSUE THREAD

**Issue by italankin** [skrugly/mirakle#53]
After upgrade to Android Studio 4.1, APK does not get installed (and run) after a successful build (Run -> Run 'app').
In the Run window I see the following error:
```
10/16 12:26:01: Launching 'app' on Emulator.
Unable to determine application id: com.android.tools.idea.run.ApkProvisionException: No outputs for the main artifact of variant: debug
```

I also tried 4.2 Canary 13 - the same story.

Android Studio 4.0.2 works fine.

Mirakle 1.3.6, macOS 10.15.7

**Comment by skrugly** [comment]
Hey, and what version of `com.android.tools.build:gradle` are you using with AS 4.1?

**Comment by italankin** [comment]
Thank you for pointing that out, I have AGP 4.0.1.
I tried 4.1.0 and it works.

Is it AS related issue?

**Comment by skrugly** [comment]
This somehow depends on the combination of AS and AGP versions.
I face this issue sometimes and glad it was resolved.
