### ISSUE TITLE
JAVA_HOME is not set and no 'java' command could be found in your PATH.

### ISSUE THREAD

**Issue by fanmingyi** [skrugly/mirakle#54]
ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

I made sure that JAVA_HOME was configured on the server.

**Comment by farmerbb** [comment]
Running into this same issue, is there anything in particular that you did to fix it?

**Comment by fanmingyi** [comment]
To start remote gradle build mirakle uses ssh which runs in non-interactive non-login mode. (Ex: ssh user@computer ./gradlew ...). Depending on your remote machine operating system distribution there are may be high chances that bash in non-interactive mode will not read any environment variables needed for your build from ~/.profile or ~/.bash_profile.

My remote is Ubuntu,so you have to do the following:

Depending on your remote machine operating system distribution there are may be high chances that bash in non-interactive mode will not read any environment variables needed for your build from ~/.profile or ~/.bash_profile.

**Comment by fanmingyi** [comment]
@farmerbb

**Comment by farmerbb** [comment]
Thanks! I was able to get it working by commenting out the following lines in my `~/.bashrc`:

```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```
