### ISSUE TITLE
Default custom gradle properties

### ISSUE THREAD

**Issue by eugene-krivobokov** [skrugly/mirakle#56]
Hi! I have custom gradle properties in the home directory (`~/.gradle/gradle.properties`).
They are not applied to a remote build. This is expected for now.
I have to duplicate them on a remote host.

It'd be great to simplify this scenario. Possible options:
- Apply them all and pass to the remote build
- Can add custom properties to `mirakle` extension

**Comment by skrugly** [comment]
Hey,

I had similar idea to introduce `mirakle_gradle.properties` and `mirakle_local.properties` files in local project dir which will be passed as `-Pname=value` to remote build. 

The presence of such new files leads to duplication of properties, but allows to define different gradle parameters for remote build, such as memory allocation, number of workers, and for example different `sdk.dir` in `mirakle_local.properties` for remote machine.

What do you think, will it work in your case?

**Comment by eugene-krivobokov** [comment]
Yes, it will do. This approach is simple and straightforward. 

There is one restriction. These files inside a project must be either per project (committed in VCS) or per user (not committed).
Now `~/.gradle/gradle.properties` is used for per-user custom settings. They are not committed as a part of the project.
I think per project will be ok. We can afford suboptimal properties for all users for the most common scenarios.

Also, I'm thinking about extensibility. Even if you decide later to pass `~/.gradle/gradle.properties` automatically these `mirakle_xxx` files can be used further as final overrides.

**Comment by skrugly** [comment]
PR #57 

Parse and pass `GRADLE_USER_HOME/gradle.properties` as `--project-prop` and `--system-prop` command line arguments to remote build.

Introduce `PROJECT_DIR/mirakle.properties` and `PROJECT_DIR/mirakle_local.properties` which can be used to pass specific gradle properties to remote build or override existing properties. Gradle properties from that files have highest priority over all other properties. Both files serves the same purpose, but `mirakle_local.properties` may be used for user specific values and skipped from commiting to VCS.
