### ISSUE TITLE
How to ignore some tasks in my assembly when building with mirakle?

### ISSUE THREAD

**Issue by SerG3z** [skrugly/mirakle#64]
how can I ignore some tasks in my assembly when building with mirakle, and when building locally, on the contrary, perform these tasks?
Example:
My settings.gradle contains
```
exec {
    commandLine 'git', 'core.hooksPath', '.githooks'
}
```
and I want to ignore this block of code if I use mirakle and vice versa

**Comment by skrugly** [comment]
Add this code block to `mirakle_init.gradle`
```
if (startParameter.taskNames.contains("assemble")) {
    startParameter.excludedTaskNames.add("myTask")    
}
```

Or you can rely on `mirakle.build.on.remote` flag which set to true when build occurs on remote machine. 
Add `onlyIf` statement to your task:
```
task myTask {
    onlyIf {
        !project.hasProperty("mirakle.build.on.remote")
    }
```

**Comment by skrugly** [comment]
@SerG3z hey, have you figured out that question?

**Comment by SerG3z** [comment]
Thanks for the answer!
This flag solved my problem.
