### ISSUE TITLE
Could not determine the dependencies of task ':app:assemble'

### ISSUE THREAD

**Issue by mohamadk** [skrugly/mirakle#65]
I'm getting sdk location not found, but the ANDROID_SDK_ROOT variable is set to sdk location in my docker container
any idea what can be  the cause?
also what should be the  value for sdk.dir in local.properties file?  

> Could not create task ':app:assembleRelease'.
   > Could not create task ':app:lintVitalRelease'.
      > SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/Users/username/AndroidStudioProjects/TestFor/local.properties'.

**Comment by skrugly** [comment]
The easiest way to fix it is to create file `local.properties` on remote machine and add `sdk.dir` to it. 
Do this:
```
ssh remote_machine
cd project_dir
touch local.properties
echo "sdk.dir=/PATH/TO/ANDROID/SDK/ON/REMOTE" > local.properties
```
local.properties file from your local machine is not copied to remote since it dosen't make sense for it.

**Comment by mohamadk** [comment]
thanks for fast reply, 
i tried your answer and it passed that step
but why it doesn't work with env variable?

**Comment by skrugly** [comment]
[I've described this problem in setup doc.](https://github.com/Adambl4/mirakle/blob/development/docs/SETUP_REMOTE.md#environment-variables)
