### ISSUE TITLE
java.io.FileNotFoundException: .gradle/6.5/executionHistory/executionHistory.lock (Permission denied)

### ISSUE THREAD

**Issue by mohamadk** [skrugly/mirakle#66]
I'm getting this error when trying build the project ,any idea why?

> Gradle could not start your build.
> Cannot create service of type TaskExecuter using method ProjectExecutionServices.createTaskExecuter() as there is a problem with parameter #17 of type ReservedFileSystemLocationRegistry.
   > Cannot create service of type ReservedFileSystemLocationRegistry using method ProjectExecutionServices.createReservedFileLocationRegistry() as there is a problem with parameter #1 of type List<ReservedFileSystemLocation>.
      > Could not create service of type ExecutionHistoryStore using ExecutionGradleServices.createExecutionHistoryStore().
         > java.io.FileNotFoundException: /Users/username/AndroidStudioProjects/TestFor/.gradle/6.5/executionHistory/executionHistory.lock (Permission denied)

**Comment by skrugly** [comment]
This error comes from local or remote build?
`./gradlew --stop` and clean build and/or reboot should help.

**Comment by mohamadk** [comment]
it's working but the after each gradle command i should run stop again unless I get this error again

**Comment by skrugly** [comment]
There are several possible solutions
[1](https://stackoverflow.com/a/32783447/6440791) [2](https://stackoverflow.com/a/56310754/6440791) [3](https://github.com/gradle/gradle/issues/6121#issuecomment-726692785) [4](https://stackoverflow.com/a/46820452/6440791)

**Comment by skrugly** [comment]
@mohamadk hey, have you resolved the issue?
