### ISSUE TITLE
Allow setup script/command to execute before gradle task

### ISSUE THREAD

**Issue by AndrewReitz** [skrugly/mirakle#67]
When trying to use mirakle I'm getting the following error

```
> Configure project :
Here's Mirakle 1.4.1. All tasks will be executed on LLAMA.

> Task :executeOnRemote

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

This is mentioned here https://github.com/Adambl4/mirakle/blob/development/docs/SETUP_REMOTE.md#environment-variables, with a TDB. I was thinking a solution would be to allow a command to execute before the gradle task. 
I think this would be as simple as changing the current ssh command to include adding user input from MirakleExcetions before the gradle command. Something like `ssh user@host config.command; gradlew task`

This would allow execution of scripts or sourcing .bashrc.

Like to know your thoughts and I'm willing to try to implement this.

**Comment by skrugly** [comment]
Hey, I like the idea, probably this will help to solve the snag.

What do you think, Is there an unveversal bash command which can be hardcoded to mirakle config and executed by default for all user to source enviroment virables from `.bashrc` and other files?

For my personal purpose `bash --login --c` works, which turns bash into login mode,  but I'm not sure how much universal it is.

**Comment by AndrewReitz** [comment]
I doubt there is a universal command, seems like there are always exceptions with shells. I was thinking of allowing some command to be configured in the Extensions. I'll see what I can figure out and report back.

I do know that you can add things to `$HOME/.ssh/rc` which will get run on ssh login but even when setting variables there I was having issues.

**Comment by AndrewReitz** [comment]
Are you passing in `bash --login -c` to the sshArgs? I think maybe what I want to do `source ~/.bashrc;` could be added as the last argument there. In which case nothing really needs to be done.

**Comment by skrugly** [comment]
>Are you passing in bash --login -c to the sshArgs? 

No, I've made a simple injection into executeOnRemote command line args for testing purpose.
```
taskGraph.whenReady { taskGraph ->
    if (taskGraph.hasTask(":executeOnRemote")) {
        def newArgs = rootProject.executeOnRemote.args
        def gradlewIndex = newArgs.findIndexOf{ it.contains("gradlew") }
        newArgs.addAll(gradlewIndex, ["bash", "--login", "-c", "\'"])
        newArgs.add("\'")
        rootProject.executeOnRemote.args = newArgs
        gradle.rootProject.executeOnRemote.doFirst {
            println("============REMOTE GRADLE ARGUMENTS===============")
            println(rootProject.executeOnRemote.args.join("\n"))
            println("============REMOTE GRADLE ARGUMENTS===============")
        }
    }
}
```

**Comment by AndrewReitz** [comment]
Ok, I ended up fixing my issue by commenting out this in my bashrc on the remote machine.

```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

I tried to make a variable to inject things but unfortunately I'm having some build issues with the plugin.
