### ISSUE TITLE
Constant rsync error: error in rsync protocol data stream (code 12)

### ISSUE THREAD

**Issue by farrellbraveheart** [skrugly/mirakle#71]
Constant:

> 
> > Configure project :
> Here's Mirakle 1.4.2. All tasks will be executed on 192.168.1.24.
> 
> > Task :uploadToRemote
> Permission denied, please try again.
> Permission denied, please try again.
> myMacOsUserName@192.168.1.24: Permission denied (publickey,password).
> rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]
> 
> > Task :fallback
> Upload to remote failed. Continuing with fallback.

RSYNC works and I installed same version on remote ubuntu machine and my macOS MacMini.

SSH works and I can connect to specified user.
Problem is that it wont connect and it fails all the time.
Uses my macOS username which I am logged on to. It does not use my specified remote username for example "android-remote-build-executor".

Android Studio: 4.1.3
Gradle Wrapper: 6.8.3

Tried all day to make it work..

**Comment by skrugly** [comment]
Have you created SSH alias in ~/.ssh/config like described [here](https://github.com/Adambl4/mirakle/blob/development/docs/SETUP_LOCAL.md#authentication)?
Then you should use that alias in mirakle config. As I can see now you are using plain ip address which lacks authentication information for the remote machine.

**Comment by farrellbraveheart** [comment]
> Permission denied (publickey,password).

This is what I get when I execute:

> ssh ubuntu

"ubuntu" is my remote device name

**Comment by skrugly** [comment]
When you said that SSH works how did you connect to remote machine?
There is nothing to do with mirakle. You should check all the steps required for establishing SSH connection.
The steps in brief:
1. Generate key
2. Create proper config for the host in ~/.ssh/config
3. Add pub key to `.ssh/authorized_keys` on remote machine

**Comment by farrellbraveheart** [comment]
using:

>  ssh userName@192.168.1.24

 works ;)

**Comment by skrugly** [comment]
Paste here your `~/ssh/config` and `mirakle_init.gradle`

**Comment by farrellbraveheart** [comment]
~/ssh/config -> empty

~/.ssh/config:

> Host ubuntu
>   User myMacOsUserName
>   HostName 192.168.1.24
>   Port 22
>   IdentityFile ~/.ssh/myMacOsUserName.pub
>   PreferredAuthentications publickey
>   ControlMaster auto
>   ControlPath /tmp/%r@%h:%p
>   ControlPersist 1h


mirakle_init.gradle:

> initscript {
>     repositories {
>         mavenCentral()
>     }
>     dependencies {
>         classpath 'io.github.adambl4:mirakle:1.4.2'
>     }
> }
>  
> apply plugin: Mirakle

Location -> /Users/myMacOsUserName/.gradle/init.d/mirakle_init.gradle

**Comment by skrugly** [comment]
IdentityFile should point to private key not public. Public key is for remote machine:
```
IdentityFile ~/.ssh/myMacOsUserName
```

**Comment by farrellbraveheart** [comment]
changed. In ~/.ssh/ there are my keys:
myMacOsUserName.pub
&
myMacOsUserName
changed to that with no extension. still te same outcome :(

**Comment by skrugly** [comment]
Do you have that lines in mirakle config?
```
rootProject {
    mirakle {
        host "ubuntu"
    }
}
```
Don't forget to save changes of file `~/.ssh/config`

**Comment by farrellbraveheart** [comment]
> Do you have that lines in mirakle config?

did you mean "mirakle_init.gradle" ?

**Comment by skrugly** [comment]
Yes, it should looks like this:
```
initscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'io.github.adambl4:mirakle:1.4.2'
    }
}
 
apply plugin: Mirakle
 
rootProject {
    mirakle {
        host "ubuntu"
    }
}
```

**Comment by farrellbraveheart** [comment]
yes its like that

**Comment by farrellbraveheart** [comment]
This time after all that changes:

> rsync error: error in rsync protocol data stream (code 255) at io.c(228) [sender=3.2.3]

**Comment by skrugly** [comment]
Does it work if you execute just `ssh ubuntu`?
Check that you have correct name in ~/.ssh/config.
```
User myMacOsUserName
```
It should be the same as in your prev command snippet `ssh userName@192.168.1.24`

**Comment by farrellbraveheart** [comment]
result of 

> ssh ubuntu

:

> Permission denied (publickey,password).

**Comment by farrellbraveheart** [comment]
During remote host configuration

which key should be pasted here "{SSH_KEY}":

> echo {SSH_KEY} >> ~/.ssh/authorized_keys

?

**Comment by skrugly** [comment]
Public key, that one which have `.pub` file extension.
Since you are able to `ssh userName@192.168.1.24` this part is configured properly.

**Comment by farrellbraveheart** [comment]
~/.ssh/authorized_keys:
/home/martin/mirakle/keys/myMacOsUserName.pub

result -

> > rsync error: unexplained error (code 255) at io.c(228) [sender=3.2.3]

~/.ssh/authorized_keys:
/home/martin/mirakle/keys/myMacOsUserName

result -

> > rsync error: unexplained error (code 12) at io.c(228) [sender=3.2.3]

**Comment by skrugly** [comment]
You should copy content of the file, not its path.
Open pub key on local machine in text editor, copy the content, write it to `~/.ssh/authorized_keys` on remote machine.
Here is an example
![image](https://user-images.githubusercontent.com/18431607/117481546-cff16f80-af6b-11eb-9a75-1366b69c6986.png)

**Comment by farrellbraveheart** [comment]
Ok done.  Same error:

> Permission denied, please try again.
> Permission denied, please try again.
> myMacOsUserName@192.168.1.24: Permission denied (publickey,password).
> rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> rsync error: error in rsync protocol data stream (code 12) at io.c(228) [sender=3.2.3]

**Comment by farrellbraveheart** [comment]
rsync log file shows:

> 2021/05/07 18:59:16 [12062] rsyncd version 3.2.3 starting, listening on port 873
> 2021/05/07 19:53:30 [12589] name lookup failed for 192.168.1.15: Name or service not known


changed the port to 873 from 22 because rsync.log states its listening on port 873

> rsyncd version 3.2.3 starting, listening on port 873

Now the error is:

> kex_exchange_identification: Connection closed by remote host
> rsync: connection unexpectedly closed (0 bytes received so far) [sender]
> rsync error: unexplained error (code 255) at io.c(228) [sender=3.2.3]


from rsyn.log:
> 2021/05/07 19:53:30 [12589] connect from UNKNOWN (192.168.1.15)

**Comment by skrugly** [comment]
Sorry It's hard to debug it remotely, I don't see where is the problem.

**Comment by farrellbraveheart** [comment]
:(
