### ISSUE TITLE
--rerun-tasks doest not get forwarded to the server

### ISSUE THREAD

**Issue by MobileSam** [skrugly/mirakle#73]
I'm trying to use the `--rerun-tasks` gradle parameter to force a re-run of all my tests and thus skip the caches. This parameter does not seem to be forwarded to the remote execution of gradlew.

**Comment by skrugly** [comment]
Hey, I've checked this param on the latest mirakle version and Gradle 7.2 and it works.
Could add this line to any `build.gradle` of your project and check the console output.
```
println("Is rerun tasks = " + gradle.startParameter.isRerunTasks())
```
if it prints true it means the parameter has been forwarded to remote machine.

**Comment by skrugly** [comment]
Please reopen if more info will arise.
