### ISSUE TITLE
Subprojects from different directory are not uploaded

### ISSUE THREAD

**Issue by avently** [skrugly/mirakle#76]
Hello. Thank you for this so useful plugin.
I have the following directory structure:
- /client/settings.gradle:
```groovy
include ':server'
project(':server).projectDir = new File('../server')
include ':common'
...other include's
```

- /server/settings.gradle
```groovy
rootProject.name = 'server'
```

As you can see, the directories `client` and `server` located near each other in parent dir. I can build `server` separately from `client` and can build `client` with `server`.
In IDEA I open `client` and see both projects. 

Mirakle doesn't upload `server` to remote machine for some reason (it only uploads `client`). If I upload `server` manually it builds `client` fine. So I probably need to somehow make it noticed about `server` existence. How to do it?

In ~/.gradle/init.d/mirakle-init.gradle
```groovy
initscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'io.github.adambl4:mirakle:1.4.2'
    }
}
 
apply plugin: Mirakle
 
rootProject {
    mirakle {
        host "my-host"
        excludeLocal += ["jars"]
        rsyncToRemoteArgs += ["--info=progress2"] 
        rsyncFromRemoteArgs += ["--info=progress2"]
    }
}
```

**Comment by avently** [comment]
Thanks, @Adambl4!

**Comment by skrugly** [comment]
Forgot to notice, you can use 1.5.0-RC-1 right now to get this working.
```
 classpath 'io.github.adambl4:mirakle:1.5.0-RC-1'
```
