### ISSUE TITLE
Ability to disable Mirakle from config

### ISSUE THREAD

**Issue by osipxd** [skrugly/mirakle#81]
For now, to be able to disable Mirakle for particular projects, we use such code:

```kotlin
initscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("io.github.adambl4:mirakle:1.4.3")
    }
}

val localPropertiesFile = File(gradle.startParameter.currentDir, "local.properties")
val properties = loadPropertiesIfExist(localPropertiesFile)
val isMirakleEnabled = properties["mirakle.enabled"]?.toBoolean() ?: true
if (isMirakleEnabled) {
    apply<Mirakle>()

    rootProject {
        configure<MirakleExtension> {
            host = "our_host"
        }
    }
}

fun loadPropertiesIfExist(file: File): Map<String, String> {
    if (!file.exists()) return emptyMap()

    val properties = java.util.Properties()
    file.inputStream().use(properties::load)

    return properties.toMap() as Map<String, String>
}
```

I think it would be great to make it configurable via `MirakleExtension` and `mirakle`/`mirakle_local.properties`:

**init.gradle.kts:**
```kotlin
apply<Mirakle>()

rootProject {
    configure<MirakleExtension> {
        host = "our_host"
        enabled = true // Default value can be set via extension
    }
}
```

**my-pet-project/mirakle_local.properties**
```properties
mirakle.enabled=false # We can manage mirakle for particular projects
```

If you approve this feature but haven't time to implement it I can make a Pull Request.

**Comment by skrugly** [comment]
Hey, thanks for the idea.
I've implemented PR which makes it possible to disable mirakle via `local.properties`.

Making it configurable via `MirakleExtension::enabled` is a little bit tricky. Mirakle works in such way than it [disables](https://github.com/Adambl4/mirakle/blob/development/plugin/src/main/kotlin/Mirakle.kt#L61) local build even before [`MirakleExtension` is initialized](https://github.com/Adambl4/mirakle/blob/development/plugin/src/main/kotlin/Mirakle.kt#L77) for sake of saving time. 

Also Gradle 8 will come with breaking changes which affects that part of plugin, I will start to prepare Mirakle for next Gradle version soon and check if it would be possible to implement such new property.
