### ISSUE TITLE
Mirakle uses project name to determine remote folder, not folder name

### ISSUE THREAD

**Issue by Mishkun** [skrugly/mirakle#85]
Problem:
If project name specified in settings.gradle like
```
rootProject.name = 'myproject'
```
mirakle fails to execute on remote with breaking on tasks enabled.

Solution:
Actual problem is with the line https://github.com/Adambl4/mirakle/blob/development/plugin/src/main/kotlin/Mirakle.kt#L111.
It takes project name instead of project directory name. rsync doesn't know anything about project, just the directory name.

**Comment by ulx** [comment]
Please check your a configuaration
`mirakle {
    host "true-remote"
    
    //optional
    remoteFolder ".mirakle"
}`
You have to change "remouteFolder"

**Comment by skrugly** [comment]
Thanks for reporting, this should be fixed in `io.github.adambl4:mirakle:1.5.0-RC-2`
Could you try it out and reopen the issue in case it dosen't work.
