### ISSUE TITLE
Support for Settings Plugin

### ISSUE THREAD

**Issue by timrijckaert** [skrugly/mirakle#89]
Hello. 

I opened a ticket on the refreshVersions page.
The author told me to open a ticket on your board. 
Could you take a look please?  

https://github.com/jmfayard/refreshVersions/issues/452

Thanks in advance.

**Comment by skrugly** [comment]
Thanks for reporting, this should be fixed in `io.github.adambl4:mirakle:1.5.0-RC-2`
Could you try it out and reopen the issue in case it dosen't work.

**Comment by timrijckaert** [comment]
Fixed! 
I noticed another [issue](https://github.com/Adambl4/mirakle/issues/95)
