### ISSUE TITLE
mirakle.gradle cause error in MirakleBreakMode

### ISSUE THREAD

**Issue by kingori** [skrugly/mirakle#90]
If I apply MirakleBreakMode plugin, mirakle.gradle cause error.

I've test like below
mirakle.gradle :
```
mirakle {
    remoteFolder "picasso"
}
```

mirakle version: 1.4.3
gradle version: 7.2

if I run gradle, I got error like below:
```
FAILURE: Build failed with an exception.

* Where:
Script '/path_to_project/mirakle.gradle' line: 1

* What went wrong:
A problem occurred evaluating script.
> Could not find method mirakle() for arguments [mirakle_54m0ji2yrs215pq1rcwy84iav$_run_closure1@5c45a1d9] on build of type org.gradle.invocation.DefaultGradle.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

It works well if I change MirakleBreakMode  to Mirakle.

**Comment by skrugly** [comment]
Thanks for reporting, this should be fixed in `io.github.adambl4:mirakle:1.5.0-RC-2`
Could you try it out and reopen the issue in case it dosen't work.
